google/cloud-android-orchestration

app/gcp/instancemanager.go
app/gcp/instancemanager_test.go
app/types.go
app/unix/instancemanager.go
main.go

- Replaces the use of experimental package `google.golang.org/genproto/googleapis/cloud/compute/v1`.

Uses `google.golang.org/api/compute/v1` package

---

app/gcp/instancemanager.go

This reverts commit de5bbbbfe4d7ba197bcf5bd80b6ef37a41ea29ff.
- Not the acloud ownership label.

Revert "Use acloud ownership label. (#24)"

---

api/v1/instancemanager.go
go.mod
go.sum
pkg/app/gcp/instancemanager.go
pkg/app/gcp/instancemanager_test.go

- Use string to properly encode the embedded objects.

[api] Change Operation response type to string.

---

app.yaml

It fails to build with 1.16 because of a dependency Version 1.19 matches the github actions.

Use runtime go119 for app engine

---

api/v1/instancemanager.go
pkg/app/controller.go
pkg/app/controller_test.go
pkg/app/errors.go
pkg/app/gcp/instancemanager.go
pkg/app/gcp/instancemanager_test.go
pkg/app/types.go
pkg/app/unix/instancemanager.go
pkg/cli/cli_test.go
pkg/client/client.go

- Return the direct result or error rather than the whole operation, having the responses for failed operations be aligned with the relevant http status code.
- Remove result property from operation object to avoid the result being queried this way.

[orchestrator] Change wait operation response.

---

pkg/webrtcclient/client_test.go

- External networking is involved (communication with STUN servers) to generate the ice candidate.

Removes non-hermetic unit test.

---

api/v1/instancemanager.go
pkg/app/gcp/instancemanager.go
pkg/app/gcp/instancemanager_test.go
pkg/cli/host.go

- "Intel Haswell" is required as min cpu platform in order to enable nested virtualization. https://cloud.google.com/compute/docs/instances/nested-virtualization/enabling
- Remove the ability to set this parameter from clients.

Fix value of Min CPU platform to "Intel Haswell".

---

api/v1/instancemanager.go
pkg/app/gcp/instancemanager.go
pkg/app/gcp/instancemanager_test.go
pkg/cli/host.go

Reverts google/cloud-android-orchestration#79
Reverting because setting "Intel Haswell"  as Min CPU platform is only required for n1-* family.

Revert "Fix value of Min CPU platform to "Intel Haswell"."

---

pkg/cli/host.go

- Former "e2-standard-4" type does not have nested virtualization enabled out of the box.

[cli] Changes gcp machine type default to "n1-standard-4".

---

cmd/cvdremote/main.go
pkg/cli/adbtunnel.go
pkg/cli/cli.go
pkg/cli/cli_test.go
pkg/cli/config.go
pkg/cli/config_test.go
pkg/cli/cvd.go
pkg/cli/host.go
pkg/client/client.go

The `cvdremote` client can be configure with a file in toml format.
The file location is passed to the executable as an environment variable to allow for different locations depending on platform. Final users are not expected to pass this variable to the command, instead when the binary is distributed it should be wrapped in a way that ensures the variable is set with the appropriate path (for example, in debian `cvdremote` should point to a script that sets the variable and executes the binary)

Make cvdremote client configurable

---

cmd/cvdremote/main.go
pkg/cli/adbtunnel.go
pkg/cli/cli.go
pkg/cli/cli_test.go
pkg/cli/cvd.go
pkg/cli/host.go
pkg/client/client.go
pkg/client/client_test.go

[cvdremote] Allows to pass different `client.Service` implementations.

---

pkg/client/client.go
pkg/client/client_test.go

- Uploading files will be done in chunks in order to be flexible with request limits set by app hosts providers. For example App Engine has a limit of 32MB https://cloud.google.com/appengine/docs/standard/quotas

[cvdremote] Upload files.

---

build/package/host/etc/cvdremote.toml
cmd/cvdremote/main.go
pkg/cli/adbtunnel.go
pkg/cli/cli.go
pkg/cli/config.go
pkg/cli/config_test.go
pkg/cli/host.go

- The `Default` prefix is not needed and it's getting carried on to new parameters for consistency purposes.

[cli] Removes `Default` prefix in config parameters.

---

pkg/cli/cli_test.go
pkg/cli/cvd.go
pkg/cli/host.go

- Create a host when `--host` flag is not passed in when creating `cvds`.

[cli] Creates host implicitly.

---

pkg/cli/cli_test.go
pkg/cli/cvd.go

- Passes the value of the newly created instance rather than the empty value from the command line.

[cli] Fixes error.

---

pkg/cli/cli_test.go
pkg/cli/conn.go
pkg/client/client.go
pkg/webrtcclient/client.go

instead of stdout, which breaks communication between connection agent and create command.

Make webrtc library log to the log files

---

pkg/app/config.go
pkg/app/gcp/instancemanager.go
pkg/app/gcp/instancemanager_test.go

Allows `acloud pull` command to work with hosts created with the cloud orchestrator.

[orchestrator] Supports `acloud pull`

---

conf.toml
pkg/app/config.go
pkg/app/net/gcp/instancemanager.go
pkg/app/net/gcp/instancemanager_test.go

- Using the image family will reference the latest image added to the family.

Use image families for declaring host image source.

---

pkg/app/instances/gce.go

- Host orchestrator now leverages cvd to create the device runtime directories.

Update acloud setup to latest changes in host orchestrator.

---

pkg/cli/cvd.go
pkg/cli/cvd_test.go

- The cvd host package tarball is required when creating local image instances.

Show error in case cvd-host_package.tar.gz does not exist.

---

pkg/app/app.go
web/page0/src/app/app.module.ts
web/page0/src/http-interceptors/cors.interceptor.spec.ts
web/page0/src/http-interceptors/cors.interceptor.ts
web/page0/src/http-interceptors/index.ts
web/page0/src/server.py

- `CorsInterceptor` in frontend & `Access-Control-Allow-Credentials` in cloud orchestrator allows HTTP requests to carry cookies
- Explicitly added allowed methods 
- Handle preflight request as specified from [MDN](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS)

Add additional settings to handle CORS

---

api/v1/instancemanager.go
cmd/cloud_orchestrator/main.go
pkg/app/app.go
pkg/app/app_test.go
pkg/app/instances/gce.go
pkg/app/instances/instances.go
pkg/app/instances/local.go

** Update **
- `GET /v1/info` became `GET /v1/config` to retreive configuration of the cloud orchestrator
- 'Runtime' concept lies on Page 0 UI and not will be revealed on cloud orchestrator side

Add missing APIs to retrieve cloud orchestration info for Page 0

---

web/page0/src/http_interceptors/auth.interceptor.ts
web/page0/src/http_interceptors/index.ts

- ~~Retry `RETRY_COUNT` times at intervals of `RETRY_INTERVAL_SEC` seconds as specified on `src/app/settings.ts`~~
- ~~Open new tab with the failed request url, as cloud orchestrators ought to redirect the request to the url for authentication~~
[ Update ]
- Simply shows snackbar if auth error happens
- Detailed error handling logic (e.g. redirect to login url) can be handled from function `handleAuthError `

Page0 Handler for failed authentication request

---

pkg/cli/cli.go
pkg/cli/cli_test.go
pkg/cli/cvd.go
pkg/cli/cvd_test.go
pkg/client/client.go

- Remove device specific WebRTCStream url and print host Web UI only.
Before:
```
1 (cf-7ed82aa8-cfcd-428e-9704-082e2338be87)
Status: Running
ADB: not connected
2 (cf-7ed82aa8-cfcd-428e-9704-082e2338be87)
Status: Running
ADB: not connected
```
After:
```
cf-7ed82aa8-cfcd-428e-9704-082e2338be87 (http://...)
1
Status: Running
ADB: not connected
2
Status: Running
ADB: not connected
```

Display hierarchical view when listing cvds.

---

api/v1/instancemanager.go
api/v1/signalingserver.go
build/package/host/usr/bin/cvdr
scripts/goutil
web/page0/README.md

Reverts google/cloud-android-orchestration#203
Breaks building the debian package as `goutil` script does no longer start with shebang (#!)

Revert "README updates and copyright headers."

---

pkg/cli/cli.go

Print non-critical errors as warnings

---

pkg/cli/cli.go
pkg/cli/cvd.go

- Flag is used to handle automatic ADB connections after the device is created.

Adds `--auto_connect` flag.

---

web/page0/src/app/refresh.service.ts
web/page0/src/app/store/store.ts

There was a possibility of losing or invalid ordering of refresh events.
Modify to send and process events in the right order.

Prevent infinite loading when runtimes length is 0

---

pkg/cli/cli.go

- Makes it specific the errors are about the canonical configuration file.

Improve error message.

---

cmd/cvdr/main.go
pkg/app/accounts/gaeusers.go
pkg/app/app.go
pkg/app/app_test.go
pkg/app/database/spanner.go
pkg/app/encryption/gcpkms.go
pkg/app/instances/hostclient.go
pkg/app/oauth2/oauth2.go
pkg/app/secrets/gcp.go
pkg/cli/adbserver.go
pkg/cli/cli.go
pkg/cli/cli_test.go
pkg/cli/config.go
pkg/cli/config_test.go
pkg/cli/conn.go
pkg/cli/cvd.go
pkg/client/client.go
pkg/client/host_orchestrator_client.go
pkg/client/httputils.go
pkg/webrtcclient/client.go
pkg/webrtcclient/client_test.go
pkg/webrtcclient/types.go

Resolved patterns:
ST1005 {error  messages}
error strings should not be capitalized
[reference](https://google.github.io/styleguide/go/decisions.html#error-strings)

Apply staticchecker linter and resolve styling  issues.

---

api/v1/instancemanager.go
pkg/app/database/spanner.go
pkg/app/errors/errors.go
pkg/app/instances/hostclient.go
pkg/cli/config.go
web/intercept/js/server_connector.js
web/page0/src/http_interceptors/auth.interceptor.ts

This commit utilizes the misspell tool to identify and correct typos and spelling mistakes across the codebase.
This improves the overall readability and clarity of the code for developers and users alike.

Eliminate Typos and Misspellings for Enhanced Readability

---

go.mod

This commit upgrades the Go language version specified in the go.mod file from go 1.18 to go 1.19. 
This addresses compatibility issues identified during testing against different Go versions.
Motivation:
- Backward compatibility testing against Go 1.18 revealed an error in pkg/cli/conn.go:159:23: undefined: atomic.Bool.
- Further investigation linked the error to the usage of atomic.Bool, which was introduced in Go 1.19.
- Reference: https://pkg.go.dev/sync/atomic#Bool
Solution:
- Upgrade Go language version to go 1.19 in the go.mod file.
This ensures compatibility with features like atomic.Bool used in the codebase.

⬆️ Upgrade Go Language Version to Address Compatibility Issues

---

build/package/host/etc/cvdr.toml
cmd/cloud_orchestrator/main.go
conf.toml
pkg/app/secrets/empty.go
pkg/app/secrets/local.go
pkg/cli/cli.go
pkg/cli/cli_test.go
pkg/cli/config.go
pkg/cli/config_test.go
pkg/cli/cvd.go

After this you can run these commands to test the system end to end:
```
$ cvd_host_orchestrator 2>ho.err >ho.out & # requires cuttlefish-user v0.9.28
$ go build ./cmd/cloud_orchestrator/ && ./cloud-orchestrator &
$ go build ./cmd/cvdr && ./cvdr --service_url=http://localhost:8080 --zone=z create --host=local --credential_source=none 
```

Make running the cloud and host orchestrators locally easy and convenient.

---

cmd/cvdr/main.go

- The config (if any) would be imported by default if not running on a terminal.

Prompt acloud config import when running on terminal only.

---

pkg/app/accounts/gaeusers.go

panic({0x144da00, 0x2415d00})
/layers/google.go.runtime/go/src/runtime/panic.go:890 +0x262
github.com/google/cloud-android-orchestration/pkg/app/accounts.(*GAEUser).Username(0x0?)
/layers/google.go.appengine-gomod/srv/pkg/app/accounts/gaeusers.go:69

Fixes nil pointer dereference.

---

scripts/presubmit.sh

This commit adds a script (presubmit.sh) that allows convenient execution of all presubmit health checks developed locally. This script can be used by team members to easily verify code quality and adherence to standards before submitting changes.
The script automatically identifies relevant checks and executes them sequentially, displaying a detailed report of the results. It also offers options for customizing the checks included and modifying the execution behavior.
This change facilitates smoother development and code quality maintenance by making presubmit checks readily accessible to the team. It also opens the possibility of sharing the script with the community for broader use and collaboration.
Bug: b/310258851

Add Script for Running Locally Developed Presubmit Health Checks

---

scripts/deploy/gae/main.sh

From: https://cloud.google.com/appengine/docs/standard/locations
```
Note: Two locations, which are called europe-west and us-central in App Engine commands and in the Google Cloud console, are called europe-west1 and us-central1, respectively, elsewhere in Google documentation.
```

Handles "europe-west" and "us-central" GAE region names.

---

cmd/cloud_orchestrator/main.go
pkg/app/instances/docker.go
pkg/app/instances/instances.go

Currently, there's no sufficient type to support containerized instance.
Of course we cannot use GCE IM type for ARM servers based on Docker.
Also using Unix IM type is restricted, since it's designed for supporting single Host Orchestrator.
In my idea, docker IM Type aims:
- Single Zone (Server itself)
- Multiple Host (One Host - One Docker instance)

Create skeleton code for IM(InstanceManager) Type - docker

---

scripts/gcp/create_host_image.sh

- compute.googleapis.com is required when creating the image.

Enable compute.googleapis.com.

---

pkg/cli/cli.go

- Remove end of line ('\n') characters, if exists, in oidc token values.

Sanitize auth token value.

---

pkg/client/host_orchestrator_client_test.go
pkg/client/httputils.go

- This bug was not reproducible when using a non nil Dumpster, why? When using a non nil dumpster `DumpResponse` (https://cs.opensource.google/go/go/+/refs/tags/go1.22.1:src/net/http/httputil/dump.go;l=305) was being called, `DumpResponse` consumes the body and replaces it with an io.nopCloser [ReadCloser], this way further reads were still possible.

Fixes  http: read on closed response body error.

---

pkg/app/app.go
pkg/app/app_test.go

Before this PR, `/v1/zones/{zone}/hosts/{host}/infra_config` didn't work because of another handling rule `/v1/zones/{zone}/hosts/{host}/{hostPath:.*}`. After this patch, cloud orchestrator will be able to modify infra configs like WebRTC STUN server information by themselves again.

Make available handling /v1/zones/{zone}/hosts/{host}/infra_config by CO

---

cmd/cloud_orchestrator/main.go
pkg/app/accounts/basic.go
pkg/app/errors/errors.go
pkg/app/instances/docker.go

This PR includes two commits:
- The first commit creates a BasicAccountManager which follows the HTTP Basic Authentication to get the username from a HTTP request.
- The second commit labels the owner of the created docker container based on the user from BasicAccountManager.

Implement http basic account manager

---

pkg/app/accounts/basic.go

The OAuth2Callback logic was refactored by https://github.com/google/cloud-android-orchestration/pull/289. We also need the same change for HTTPBasicAccountManager.

Refactor OAuth2Callback for HTTPBasicAccountManager

---

pkg/cli/cvd.go
pkg/cli/cvd_test.go

After running `lunch`, ANDROID_HOST_OUT is set as `$ANDROID_BUILD_TOP/out/host/linux-x86`. To be run in ARM64 dockerized instance, we should send `cvd-host_package.tar.gz` for ARM64.

Change HostOut path for ARM64 during cvdr create

---

pkg/cli/cli.go
pkg/cli/config.go
pkg/client/client.go
pkg/client/httputils.go

Always permit users to access the homepage and the cloud_orchestrator config without specifying their username. Users can get the account manager type accordingly to decide whether they should set their username in following HTTP requests.

Implement http basic auth for cvdr.

---

api/v1/instancemanager.go
pkg/app/instances/docker.go

With this PR, in `GET /v1/zones/local/hosts`,
```
{
"items": [
{
"name": "3b035d58d90d22ecf97c735640567ad81528e5e9fbce38b24a44349214527d9f",
"docker": {
"image_name": "cuttlefish:latest",
"ip_address": "172.17.0.2"
}
}
]
}
```
We can get IP address information of docker instance. I'm having a plan to use this information by `cvdr connect`.

Expose IP Address of docker instance via ListHosts

---

cmd/cloud_orchestrator/main.go
pkg/app/accounts/usernameonly.go

- Renaming this account manager because it was designed for closed deployed cloud orchestrator. Although we leverage the HTTP basic authentication, only username is used.
- Tests:
- `cvdr create`
- `cvdr list`
- `cvdr delete`

Rename HTTPBasicAccountManager to UsernameOnlyAccountManager.

---

go.mod
go.sum
pkg/cli/adbserver.go
pkg/cli/cli.go
pkg/cli/cli_test.go
pkg/cli/conn.go
pkg/cli/cvd.go
pkg/cli/host.go

How to turn on `--connect_agent` flag with `proxy_agent` in `cvdr connect`:
```
./cvdr \
--http_proxy=socks5://localhost:1337 \
--service_url=http://100.114.242.57:8080 \
--zone=local \
--host=$CO_HOST_NAME \
--connect_agent=proxy_agent \
connect
```
Currently this PR needs some fixes:
- Agent process should be terminated(Make it being daemonized): WIP

Introduce --connect_agent with the new type(proxy_agent) into cvdr connect

---

pkg/app/accounts/usernameonly.go
pkg/app/app.go

- To customize the user input when using a browser to interact with cloud_orchestrator.

Add /username endpoint for UsernameOnlyAccountManager to log username.

---

README.md
docs/cloud_orchestrator.md
docs/cvdr.md

To write a new document under [source.android.com](https://source.android.com/), we need a document to define what's Cloud Orchestrator and cvdr. I thought here's the better place than [source.android.com](https://source.android.com/).
CWL(Cuttlefish Web Launcher, Page 0) is not scope of this PR for providing detail in public.

Write documentation about definition of Cloud Orchestrator and cvdr.

---

cmd/cvdr/main.go
pkg/cli/config.go
pkg/cli/config_test.go

- Parsing a combined blob is not correct as top level fields needs to be listed at the beginning for a correct parsing.

Parse system and user configuration files independently.

---

pkg/app/instances/gce.go
pkg/app/instances/gce_test.go
scripts/gcp/app/conf.toml.tmpl

This PR makes `network` and `subnetwork` configurable via the `conf.toml` if GCP is used to deploy instances.  At the moment it is statically set in the `cloud-orchestrator` but we could also make this configurable on a `cvdr host create` request basis.

feat: make network and subnetwork configurable

---

pkg/app/instances/hostclient.go

- Adds `x-cutf-proxy` header to failed proxy responses to localize the relevant proxy from final response.

Logs request path on proxy errors.

---

pkg/cli/authz/oauth.go
pkg/cli/cvd.go

- Add a new package `authz` for the authorization
- Move the `jwtAccessToken` in `authz` package
- Implemenet the 3LO auth flow for end users

Get access token for Build API via 3LO OAuth flow

---

pkg/cli/cli.go

Changed to use --zone and --host flag to find adb WebSocket backend.
When --host=none, use service_url as before (Directly connect to service_url) to support host orchestrator only case.

Change cvdr websocket connect agent to follow cvdr command scheme

---

pkg/cli/cli.go
pkg/cli/cli_test.go
pkg/client/client.go
pkg/client/host_orchestrator_client.go
pkg/client/httputils.go

WebSocket connection needs to follow Proxy configuration and Authorization configuration to connect adb websocket backend through Cloud Orchestrator. Change to use same config and header as normal HTTP request does.

Align WebSocket connection request with normal HTTP request at cvdr

---

pkg/cli/cli.go
pkg/cli/cvd.go

- The value of this flag determines how the build api access token is retrieved only, let's be specific about it in the name.

Use build api credentials source from config

---

.gitignore
Dockerfile
cmd/cloud_orchestrator/main.go
pkg/app/accounts/iap.go
pkg/app/instances/gce.go
pkg/app/instances/gce_test.go
scripts/gcp/cloudrun/.terraform.lock.hcl
scripts/gcp/cloudrun/README.md
scripts/gcp/cloudrun/build-and-deploy.sh.tmpl
scripts/gcp/cloudrun/conf.toml.tmpl
scripts/gcp/cloudrun/main.tf
scripts/gcp/cloudrun/variables.tf

This PR adds the Terraform setup and the necessary changes to Cloud Orchestrator to be deployed on Cloud Run protected by IAP. Additionally it includes the possibility to use GCE instances with private IPs only.
Co-authored-by: David Gleich <gleichda@google.com>

feat: add Cloud Run deployment

---

pkg/cli/cli.go

Kept the close in the same goroutine where it's written to to prevent potential SIGPIPE errors.

Avoid double close of wsWrapper

---

build/debian/cuttlefish_cvdremote/host/etc/cvdr.toml

Without this change, `cvdr` cannot invoke its help message due to its configuration value.
```
$ cvdr --help
error loading system configuration: undecoded keys: ["Host.GCP.MachineType"]
```

Comment all configuration in cvdr.toml for cuttlefish-cvdremote

---

scripts/gcp/app/app.yaml.tmpl

Go Runtime 1.19 is deprecated, updating to the latest supported version

Updated GAE Go runtime to 1.22

---

api/v1/instancemanager.go
pkg/app/instances/gce.go

The compute instance insert API requires the accelerator type to be a full or partial URL of the accelerator type resource

Fixed acceleratorType value

---

go.mod
go.sum
pkg/cli/testing.go

As https://github.com/google/android-cuttlefish/pull/1397 is merged, add corresponding implementation on `fakeHostService` in advance.

Bump up modules from github.com/google/android-cuttlefish

---

.gitignore
e2etests/MODULE.bazel
e2etests/cvdr/BUILD.bazel
e2etests/cvdr/README.md
e2etests/cvdr/common_utils.sh
e2etests/cvdr/cvdr_host_create_test.sh

Based on the design at go/cvdr-e2e-test-dd, this PR contains the rough impl of cvdr E2E test with the simplest test case(`cvdr host create`).
Presubmit check should be appended in the following PR. (https://github.com/google/cloud-android-orchestration/pull/441)

Define cvdr E2E test

---

go.mod
go.sum
pkg/cli/cvd.go
pkg/cli/testing.go

This PR requires to have patches from Host Orchestrator suggested at https://github.com/google/android-cuttlefish/pull/1402, but I request the review on this PR in advance for the visibility to review corresponding HO changes. Details about canonical config is explained at there as well.
This PR also suggests to integrate `createCVDFromLocalBuild` or `createCVDFromLocalSrcs` into `createWithCanonicalConfig`, since those are already builds canonical config to pass it when creating CF instances.

cvdr create uses new HO APIs for dealing with user artifact & image dir

---

go.mod
go.sum
pkg/cli/cvd.go
pkg/cli/cvd_test.go

This reverts commit 91fae399a37f09478b0fc1f6c351e9da0ad6d52d.
One of the introduced dependencies requires go 1.22 which is not available on all platforms and is not required in the debian control file.
Bug=b/433332364

Revert "Check that EnvConfig is convertible to proto."

---

go.mod
go.sum
pkg/cli/cvd.go
pkg/cli/cvd_test.go

Since the EnvConfig is converted to proto on the other end, check for errors by converting to proto on this end. Since we exported the proto in google/android-cuttlefish#1358, we can import it directly to use it.
(This commit re-lands #437 after revert in #443, ensuring it builds properly on a bookworm container running go 1.19.)

Re-land #437 "Check that EnvConfig is convertible to proto."

---

go.mod
go.sum
pkg/cli/testing.go

This patch is required to obtain `ListImageDirectories` and `DeleteImageDirectory`.

Bump up modules from google/android-cuttlefish

---

pkg/cli/cli.go
pkg/cli/cvd.go

Because it's not thread safe. Removed the locking logic since it can't be used in multithreaded code anyways.

Don't use statePrinter inside goroutines

---

.github/workflows/deployment.yaml

Postsubmit procedure about deployment of docker image was broken. Sorry for that.

Fix typo around postsubmit GH workflow
