- app/gcp/instancemanager.go
- app/gcp/instancemanager_test.go
- main.go
* Use Google Application Default Credentials for authentication.
> Use a single `compute service` instance.

- app/controller.go
- app/controller_test.go
- main.go
- Adds simple test case for create host endpoint.
> Make controller testable.

- api/v1/instancemanager.go
- app/gcp/instancemanager.go
- app/gcp/instancemanager_test.go
> Use image size only to set the boot disk size

- pkg/cli/cli.go
- pkg/client/client.go
- pkg/webrtcclient/client.go
- pkg/webrtcclient/client_test.go
Adds webrtc connection capabitlity to the api client
Makes webrtc connections close cleanly by ensuring all goroutines stop
> Advance towards adb tunnel command

- pkg/cli/cli_test.go
- pkg/client/client.go
- Based on https://github.com/google/cloud-android-orchestration/pull/60 change.
> [cli] Update operation wait endpoint.

- pkg/cli/adbtunnel.go
The behavior is guarded by a flag (-c | --connect). The default value is `false` since most developer workstations don't have the `adb` command in the path until `envsetup.sh` is sourced and `lunch` is executed.
> Connect adb on `adbtunnel create`

- api/v1/instancemanager.go
- api/v1/signalingserver.go
- pkg/app/controller.go
- pkg/app/controller_test.go
- pkg/app/gcp/instancemanager.go
- pkg/app/gcp/instancemanager_test.go
- pkg/app/signalingserver.go
- pkg/app/types.go
- pkg/app/unix/instancemanager.go
- pkg/cli/cli_test.go
- pkg/client/client.go
- pkg/client/client_test.go
- pkg/webrtcclient/client.go
- pkg/webrtcclient/client_test.go
- pkg/webrtcclient/types.go
> Replace interface{} with any

- pkg/cli/adbtunnel.go
The ADBForwarder has a state.
A status command is accepted through the control socket
> Differentiate between status and state

- pkg/cli/adbtunnel.go
This avoids restarting the server unintentionally and eliminates the need to control the connection with a flag.
> Connect ADB through ADB server control socket instead of via command

- pkg/cli/cli_test.go
- Use a fake implementation of client.Service and remove existing logic based on http calls.
> [cli] Use fake service implementation in unit tests.

- cmd/cvdr/main.go
- This update was skipped in https://github.com/google/cloud-android-orchestration/pull/121
> Update env variable name.

- pkg/cli/cli.go
instead of the global channels from os.Std*.
This makes it more test-friendly
> Connection agent closes the command's IO channel instead of the global ones

- cmd/cvdr/main.go
- pkg/cli/adbserver.go
- pkg/cli/cli.go
- pkg/cli/cli_test.go
- pkg/cli/conn.go
which avoids spurious error messages in tests
> Make comms with the ADB server fakeable

- pkg/app/net/hostclient.go
That object has a mutex, that if copied while locked will make the resulting Transport unusable. Instead create a new object and only copy those fields that are modified when the default is created.
> Don't copy http.DefaultTransport

- pkg/app/net/unix/encryption.go
To make it really obvious that SimpleEncryptionService is not a real encryption service and should never be used for anything other than development and testing.
> Don't use actual encryption algorithms for local development

- cmd/cloud_orchestrator/main.go
- conf.toml
- pkg/app/accounts/accounts.go
- pkg/app/accounts/gaeusers.go
- pkg/app/accounts/unix.go
- pkg/app/app.go
- pkg/app/app_test.go
- pkg/app/config/config.go
- pkg/app/instances/gce.go
- pkg/app/instances/gce_test.go
- pkg/app/instances/instances.go
- pkg/app/instances/local.go
- pkg/app/oauth2/oauth2.go
- pkg/app/secrets/gcp.go
- pkg/app/secrets/local.go
- pkg/app/secrets/secrets.go
- pkg/app/signaling/signalingserver.go
Some renames, unused code deletions and moved the webrtc configuration to the signaling server.
> Finish refactoring packages under pkg/app

- go.mod
- go.sum
- pkg/cli/cli.go
- pkg/cli/cli_test.go
- pkg/cli/cvd.go
- pkg/client/client.go
- Host Orchestrator changed its response object for create cvd requests.
> [cli] Updated to the latest changes in Host Orchestrator web API.

- pkg/cli/cli.go
- pkg/cli/cvd.go
- pkg/cli/cvd_test.go
- `--num_instances` allows to create multiple homogeneous instances.
> [cli] Adds --num_instances flag

- pkg/cli/cli.go
- Improve message cosmetics using fixed length messages.
> Use OK/Failed tokens rather than generic Done.

- pkg/cli/cli.go
- pkg/cli/cli_test.go
- pkg/cli/host.go
- pkg/client/client.go
- Download runtime artifacts bundle.
> [cli] cvdr pull

- pkg/client/client.go
- Required after https://github.com/google/cloud-android-orchestration/commit/8641201b9e6080800a4eb8abaca7691f11a4b327
> Update polled_connection endpoints.

- pkg/cli/cli.go
- pkg/cli/cli_test.go
- pkg/cli/conn.go
- pkg/client/client.go
- pkg/webrtcclient/types.go
- Allows the user to use a customized ICE config when using `cvdr connect`.
> Use local ICE config.

- pkg/cli/conn.go
because closing it twice causes a panic
> Close the Forwarder's ready channel only once

- web/page0/src/app/app.module.ts
- web/page0/src/app/env-card/env-card.component.ts
- web/page0/src/app/list-runtime-view/list-runtime-view.component.html
- web/page0/src/app/list-runtime-view/list-runtime-view.component.ts
- web/page0/src/app/register-runtime-view/register-runtime-view.component.html
- web/page0/src/app/register-runtime-view/register-runtime-view.component.ts
- web/page0/src/app/runtime-card/runtime-card.component.html
- web/page0/src/app/runtime-card/runtime-card.component.ts
- web/page0/src/app/runtime-interface.ts
- web/page0/src/app/runtime.service.ts
- web/page0/src/app/settings.ts
- Most of List Runtime view & Register Runtime view
- Retrieving zones, hosts, and groups from cloud orchestrator will be on seperate PR
> Page 0 runtime management features

- pkg/app/app.go
- pkg/app/app_test.go
- Use http header to request build api credentials injection in cloud orchestrator.
> Inject build api creds in relevant http header.

- pkg/cli/cli.go
- pkg/cli/cli_test.go
- pkg/cli/conn.go
- pkg/cli/cvd.go
- pkg/cli/cvd_test.go
- New names aim to be more specifc.
> [cvdr] Rename `cvd` related structs.

- web/page0/src/app/active-env-pane/active-env-pane.component.ts
- web/page0/src/app/api.service.ts
- web/page0/src/app/create-env-view/create-env-view.component.html
- web/page0/src/app/create-env-view/create-env-view.component.ts
- web/page0/src/app/create-host-view/create-host-view.component.ts
- web/page0/src/app/env-card/env-card.component.ts
- web/page0/src/app/env-form.service.ts
- web/page0/src/app/env.service.ts
- web/page0/src/app/fetch.service.ts
- web/page0/src/app/host.service.ts
- web/page0/src/app/interface/cloud-orchestrator.dto.ts
- web/page0/src/app/interface/component-interface.ts
- web/page0/src/app/interface/host-interface.ts
- web/page0/src/app/interface/runtime-interface.ts
- web/page0/src/app/interface/utils.ts
- web/page0/src/app/interface/wait-interface.ts
- web/page0/src/app/list-runtime-view/list-runtime-view.component.html
- web/page0/src/app/operation.service.spec.ts
- web/page0/src/app/operation.service.ts
- web/page0/src/app/refresh.service.ts
- web/page0/src/app/register-runtime-view/register-runtime-view.component.ts
- web/page0/src/app/runtime-card/runtime-card.component.html
- web/page0/src/app/runtime-card/runtime-card.component.ts
- web/page0/src/app/runtime.service.ts
- web/page0/src/app/settings.ts
- web/page0/src/app/store/actions.ts
- web/page0/src/app/store/reducers.ts
- web/page0/src/app/store/selectors.ts
- web/page0/src/app/store/state.ts
- web/page0/src/test_apis.py
- Should be merged after #191 
- Add long polling for host creation, host deletion, and env creation
- Host deletion updates corresponding environment to be status "stopping"
> Page0 long polling for hosts and environments

- api/v1/instancemanager.go
- api/v1/signalingserver.go
- build/package/host/usr/bin/cvdr
- scripts/goutil
- web/page0/README.md
This changes is for minor cleanup and testing development flow .
> README updates and copyright headers.

- pkg/cli/conn.go
That prevents cleanup code from unlinking the unix sockets
> Don't panic from connection agent processes

- cmd/cvdr/main.go
- pkg/app/app.go
- pkg/cli/cli.go
- pkg/cli/cli_test.go
- pkg/cli/config.go
- pkg/cli/conn.go
- pkg/cli/cvd_test.go
- pkg/client/host_orchestrator_client.go
- pkg/client/httputils.go
- pkg/webrtcclient/client_test.go
This commit addresses various errors and warnings flagged by the staticcheck linter, promoting best coding practices within the Golang codebase.
These fixes include:
- Error Handling: Improved error checking and handling across various functions.
- Unnecessary Code: Removed redundant or unused code snippets for improved clarity and maintainability.
- Naming Conventions: Optimized variable and function names to follow established naming conventions.
- Type Conversions: Corrected potential type conversion issues to ensure accurate data handling.
- Replacemnnt of obsolete APIs
By addressing these staticcheck issues, we ensure the codebase adheres to best practices, enhancing its overall readability, maintainability, and performance.
Bug: b/309718654
> Fix Staticcheck Linter Issues for Improved Code Quality

- docs/development.md
This commit corrects the instructions for building the host orchestrator binary in the developer documentation.
This ensures that future developers can easily follow the correct steps and successfully build the binary without encountering any roadblocks.
> Fix Developer Instructions: Building the Host Orchestrator Binary

- go.mod
- go.sum
- pkg/cli/cli.go
- pkg/cli/config.go
- The new command is an utility to fetch the final configuration parameter values.
> Adds `get_config` command.

- pkg/cli/cli.go
- pkg/cli/cli_test.go
- pkg/client/host_orchestrator_client.go
- Allows to delete cvd instances in the host.
> Adds `cvdr delete` subcommand.

- pkg/app/instances/docker.go
- pkg/app/instances/docker_test.go
This PR is needed to support using `cvdr host create` and `cvdr host delete`.
> Implement WaitOperation of dockerIMType

- pkg/cli/cvd.go
- pkg/cli/cvd_test.go
- Compute the values independently. In arm64 builds the HostOut cannot be computed this way.
> Remove AndroidEnvVars struct.

- pkg/app/instances/docker.go
This PR is just for refactoring and optimization, but following change will be able to grab IP address of docker instance, to do adb connection via cvdr.
> Change host address of docker instance

- docs/docker.md
- scripts/docker/run.sh
https://github.com/google/cloud-android-orchestration/pull/308#discussion_r1600354229
> scripts/docker/run.sh uses go run.

- build/package/host/etc/cvdr.toml
- docs/docker.md
- pkg/cli/cli.go
- pkg/cli/config.go
- pkg/cli/config_test.go
> Rename HTTPProxy as Proxy in cvdr

- pkg/cli/cli.go
When WebSocket connection error is occured, current implementation sends result as success becuase it tries to send result before reporting result. The error messahe also not shown because standard IOs are closed.
Try to connect WebSocket before sending result to parent to fix this.
> Try to connect WebSocket and return error before send result to parent

- pkg/client/httputils.go
- Violation happened when writing to a nil `DumpOut`.
> Fixes nil pointer dereference.

- pkg/cli/cli.go
- pkg/cli/cvd.go
- pkg/client/client.go
- pkg/client/host_orchestrator_client.go
For more information, please refer to b/353884144#comment13
> Support JWT auth flow that access tokens are managed by cvdr

- pkg/cli/config.go
- pkg/cli/config_test.go
- Fixes npd when there's no service in user config.
> Fixes null pointer dereference.

- pkg/cli/cli.go
- pkg/client/client.go
- Logs url requires the group name.
> Fixes logs url.

- web/page0/src/app/active-env-pane/active-env-pane.component.ts
- web/page0/src/app/app.component.ts
- web/page0/src/app/create-env-view/create-env-view.component.ts
- web/page0/src/app/create-host-view/create-host-view.component.ts
- web/page0/src/app/device-form/device-form.component.ts
- web/page0/src/app/env-card/env-card.component.ts
- web/page0/src/app/env-list-view/env-list-view.component.ts
- web/page0/src/app/list-runtime-view/list-runtime-view.component.ts
- web/page0/src/app/register-runtime-view/register-runtime-view.component.ts
- web/page0/src/app/runtime-card/runtime-card.component.ts
- web/page0/src/app/safe-url.pipe.ts
https://blog.angular.dev/the-future-is-standalone-475d7edbc706
> Set `standalone: false` to prepare for Angular v19

- pkg/cli/cli.go
- pkg/cli/cli_test.go
- pkg/cli/cvd.go
- pkg/client/host_orchestrator_client.go
- pkg/client/host_orchestrator_client_test.go
This PR depends on [google/android-cuttlefish#698](https://github.com/google/android-cuttlefish/pull/698).
> Support user project override

- pkg/webrtcclient/client.go
Include webrtc Session Descriptions and ICE candidates, as well as debug level logging from the pion/webrtc library.
> Add more logging for cvdr connection agent

- docs/cvdr.md
For the visibility from the user's perspective.
> Mention cvdr --help in docs/cvdr.md

- go.mod
- go.sum
- pkg/cli/cli_test.go
- pkg/cli/cvd.go
- pkg/client/client.go
- Use new api to handle the Build API credentials.
> Bump libhoclient version.

- cmd/cloud_orchestrator/main.go
- scripts/docker/run.sh
This makes Cloud Orchestrator possible to connect to docker servie with older version than docker client library.
> Add client.WithAPIVersionNegotiation() option for Docker client

- pkg/cli/cli.go
WebSocket connection is closed when it is idle for a while. Write ping message for every 10 seconds to prevent idle timeout for ADB websocket connection.
> Write ping message for preventing idle timeout for ADB websocket

- pkg/cli/cli.go
> Send `gcp_accelerator` parameter on `host create`

- pkg/cli/testing.go
> Implement PowerBtn in fakeHostService

- pkg/cli/testing.go
> Correct spelling of Powerbtn function

- pkg/cli/cli.go
This prevents infinite waiting in the case that the ADB server does not respond to the ADB connect request.
> Add timeout for Listen() while waiting for connection from ADB server.

- go.mod
- go.sum
- pkg/cli/cli.go
- pkg/cli/testing.go
> Bump github.com/google/android-cuttlefish/frontend/src/liboperator

- go.mod
- go.sum
- pkg/cli/testing.go
Background context: https://github.com/google/android-cuttlefish/pull/1393#discussion_r2205974518
> Bumpup modules from github.com/google/android-cuttlefish

- scripts/on-premises/single-server/cvdr_create_multiple_hosts.sh
Context: comments from https://github.com/google/cloud-android-orchestration/pull/448 after merge
> Refactor cvdr_create_multiple_hosts.sh

- go.mod
- go.sum
- pkg/cli/cli.go
> Implement `cvdr reset --host={host}`

- go.mod
- go.sum
- pkg/cli/cli.go
- pkg/cli/cvd.go
> Upgrade libhoclient dependency

- .github/actions/build-cuttlefish-cvdremote-debian-package/action.yaml
- .github/workflows/presubmit.yaml
> Build cuttlefish-cvdremote for ARM64 on presubmit
